# Generated by Django 2.1.4 on 2018-12-22 19:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdc_name', models.CharField(max_length=50)),
                ('zone_name', models.CharField(max_length=16)),
                ('region', models.CharField(max_length=16)),
                ('dist_name', models.CharField(max_length=29)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
