# Generated by Django 2.1.4 on 2018-12-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disthq', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldBorder',
            new_name='DistrictHeadquaters',
        ),
    ]
