# Generated by Django 2.1.4 on 2018-12-22 19:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disthq', '0002_auto_20181223_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtheadquaters',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
