# Generated by Django 2.1.4 on 2018-12-23 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NepalDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_sq_km', models.FloatField()),
                ('zone_name', models.CharField(max_length=50)),
                ('dist_code', models.IntegerField()),
                ('district', models.CharField(max_length=20)),
                ('pop_total', models.IntegerField()),
                ('pop_male', models.IntegerField()),
                ('pop_female', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
