# Generated by Django 2.1.4 on 2018-12-23 14:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrypopn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepaldistrict',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
